"""Summary/analytics endpoints used to power a dashboard UI."""
import logging

import pandas as pd
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from app.core.config import get_settings
from app.schemas import ClusterInfo
from app.services.db import get_db

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/dashboard", tags=["Dashboard"])


@router.get("/clusters", response_model=list[ClusterInfo])
def get_circle_clusters():
    settings = get_settings()
    path = settings.models_path / "circle_clusters.csv"
    if not path.exists():
        raise HTTPException(503, "Cluster data not found — run the training pipeline first.")

    df = pd.read_csv(path)
    return df.to_dict(orient="records")


@router.get("/image")
def get_final_dashboard_image():
    """Serves the final analytics dashboard PNG generated by generate_reports.py."""
    settings = get_settings()
    path = settings.reports_path / "gridmind_dashboard.png"
    if not path.exists():
        raise HTTPException(
            503, "Dashboard image not found — run 'python generate_reports.py' after training."
        )
    return FileResponse(path, media_type="image/png")


@router.get("/summary")
def dashboard_summary():
    db = get_db()
    if db is None:
        return {"total_records": 0, "anomaly_count": 0, "platform": "GridMind AI", "status": "db_offline"}

    total = db.telemetry.count_documents({})
    anomaly = db.alerts.count_documents({"is_anomaly": True})
    return {"total_records": total, "anomaly_count": anomaly, "platform": "GridMind AI", "status": "live"}
