"""Summary/analytics endpoints used to power a dashboard UI."""
import logging

import pandas as pd
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from app.core.config import get_settings
from app.schemas import ClusterInfo
from app.services.db import get_db

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/dashboard", tags=["Dashboard"])


@router.get("/clusters", response_model=list[ClusterInfo])
def get_circle_clusters():
    settings = get_settings()
    path = settings.models_path / "circle_clusters.csv"
    if not path.exists():
        raise HTTPException(503, "Cluster data not found — run the training pipeline first.")

    df = pd.read_csv(path)
    return df.to_dict(orient="records")


@router.get("/image")
def get_final_dashboard_image():
    """Serves the final analytics dashboard PNG generated by generate_reports.py."""
    settings = get_settings()
    path = settings.reports_path / "gridmind_dashboard.png"
    if not path.exists():
        raise HTTPException(
            503, "Dashboard image not found — run 'python generate_reports.py' after training."
        )
    return FileResponse(path, media_type="image/png")


import json

@router.get("/summary")
def dashboard_summary():
    db = get_db()
    if db is not None:
        try:
            total = db.telemetry.count_documents({})
            anomaly = db.alerts.count_documents({"is_anomaly": True})
            if total > 0:
                return {
                    "total_records": total,
                    "anomaly_count": anomaly,
                    "circles": 16,
                    "platform": "GridMind AI",
                    "status": "live_db"
                }
        except Exception as e:
            logger.warning("DB query failed, falling back to cache: %s", e)

    settings = get_settings()
    summary_path = settings.reports_path / "training_summary.json"
    if summary_path.exists():
        try:
            with open(summary_path) as f:
                data = json.load(f)
            return {
                "total_records": data.get("rows_processed", 156294),
                "anomaly_count": data.get("isolation_forest", {}).get("anomalies_detected", 7815),
                "circles": data.get("circles", 16),
                "platform": "GridMind AI",
                "status": "cached_dataset"
            }
        except Exception as e:
            logger.warning("Failed to read training summary: %s", e)

    return {
        "total_records": 156294,
        "anomaly_count": 7815,
        "circles": 16,
        "platform": "GridMind AI",
        "status": "offline_default"
    }


@router.get("/circles")
def get_circles_list():
    """Returns list of all available grid circles and their representative profiles."""
    settings = get_settings()
    path = settings.models_path / "circle_clusters.csv"
    if path.exists():
        df = pd.read_csv(path)
        return {
            "circles": df["Circle"].tolist(),
            "details": df.to_dict(orient="records")
        }
    return {
        "circles": [
            "ADILABAD", "ASIFABAD", "BHADRADRI KOTHAGUDEM", "BHUPALAPALLY",
            "HANUMAKONDA", "JAGITYAL", "JANGAON", "KAMAREDDY",
            "KARIMNAGAR", "KHAMMAM", "MAHABUBABAD", "MANCHERIAL",
            "NIRMAL", "NIZAMABAD", "PEDDAPALLY", "WARANGAL"
        ],
        "details": []
    }

